#ifndef k1_burst_common_h
#define k1_burst_common_h
#include "k1-burst-driver.names.h"

#include K1_PFR_CONFIG
#include K1_MOTOR_CONFIG

#define K1_PWM_MODULO ( K1_CPU_FREQ_HZ* K1_PWM_PERIOD_US / 2000000L  - 1L )
#define K1_ADC_DELAY ( K1_CPU_FREQ_HZ* K1_ADC_CURRENT_SENCE_TIME_US / 1000000L  - 1L )

#define K1_CONTROL_PERIOD_US (K1_PWM_PERIOD_US * K1_PWM_TIMER_PRESC)

#define K1_FREEMASTER_TYPE_NONE								0
#define K1_FREEMASTER_TYPE_OV_SERIAL_1				1
#define K1_FREEMASTER_TYPE_OV_SERIAL_2				2
#define K1_FREEMASTER_TYPE_OV_SERIAL_3				4
#define K1_FREEMASTER_TYPE_OV_FLOW_PROTO			5
#define K1_FREEMASTER_TYPE_OV_SWITCH_ABONENT	6
#define K1_FREEMASTER_TYPE_DIRRECT	7

#ifndef K1_SERIAL_SIZE
#define K1_SERIAL_SIZE 255
#endif

#ifndef TMP423_ENABLED
#define TMP423_ENABLED 0
#endif


#define K1_MOTOR_CURRENT_PP_TO_A(pp) ((burst_signal_t)(((burst_long_signal_t)(K1_MOTOR_CURRENT_PP_TO_A_GAIN_15*pp))>>15))
#define K1_MOTOR_CURRENT_A_TO_PP(a) ((burst_signal_t)(((burst_long_signal_t)(K1_MOTOR_CURRENT_A_TO_PP_GAIN_15*a))>>15))

#define K1_MOTOR_CURRENT_PP_TO_MA(pp) ((burst_signal_t)(((burst_long_signal_t)(K1_MOTOR_CURRENT_PP_TO_MA_GAIN_10*pp))>>10))
#define K1_MOTOR_CURRENT_MA_TO_PP(ma) ((burst_signal_t)(((burst_long_signal_t)(K1_MOTOR_CURRENT_MA_TO_PP_GAIN_10*ma))>>10))

#if K1_BOARD_COMMON_VER <2
#ifndef K1_BOARD_TEMPER_PP_TO_GRAD
#define K1_BOARD_TEMPER_PP_TO_GRAD( pp )\
(\
	(burst_signal_t)((\
		(int) (K1_BOARD_TEMPER_SENCE_REFER_TEMPER*65536 - K1_BOARD_TEMPER_SENCE_REFER_VOLT*4096*1000*16/K1_BOARD_TEMPER_SENCE_grad2mVolt)\
		+(int) (3.3* 1000*16/K1_BOARD_TEMPER_SENCE_grad2mVolt)*pp +32767\
	)>>16)\
)
#endif
		

#ifndef K1_BOARD_TEMPER_GRAD_TO_PP
#define K1_BOARD_TEMPER_GRAD_TO_PP( gr )\
(\
	(burst_signal_t)((\
		(int)(K1_BOARD_TEMPER_SENCE_REFER_VOLT/3.3*4098*65536  - K1_BOARD_TEMPER_SENCE_REFER_TEMPER*K1_BOARD_TEMPER_SENCE_grad2mVolt/1000/3.3*4098*65536)\
		+ (int)(K1_BOARD_TEMPER_SENCE_grad2mVolt/1000/3.3*4098*65536) * gr\
	)>>16)\
)	
#endif
#else

#ifndef BOARD_TEMPER_SENCE_ABC_ENABLED
#define BOARD_TEMPER_SENCE_ABC_ENABLED 0
#endif

#ifndef BOARD_TEMPER_SENCE_Z_ENABLED
#define BOARD_TEMPER_SENCE_Z_ENABLED 0
#endif

#ifndef BOARD_TEMPER_SENCE_MK_ENABLED
#define BOARD_TEMPER_SENCE_MK_ENABLED 0
#endif


#endif

#endif
		
#ifndef BOARD_VOLTAGE_SENCE_ENABLED 		
#define BOARD_VOLTAGE_SENCE_ENABLED 	0
#endif

#if BOARD_VOLTAGE_SENCE_ENABLED 
#define 		K1_BOARD_VOLTAGE_PP_TO_VOLT_GAIN_16 ((burst_long_signal_t)(K1_BOARD_VOLTAGE_PP_TO_CVOLT_GAIN_10/6.4))
#define 		K1_BOARD_VOLTAGE_PP_TO_VOLT_OFFSET_16 ((burst_long_signal_t)(K1_BOARD_VOLTAGE_PP_TO_CVOLT_OFFSET_10/6.4))

#define K1_BOARD_VOLTAGE_VOLT_TO_PP_GAIN_16 ((burst_long_signal_t)(K1_BOARD_VOLTAGE_CVOLT_TO_PP_GAIN_10*6.4))
#define K1_BOARD_VOLTAGE_VOLT_TO_PP_OFFSET_16 ((burst_long_signal_t)(K1_BOARD_VOLTAGE_CVOLT_TO_PP_OFFSET_10*6.4))

#define K1_BOARD_VOLTAGE_PP_TO_VOLT(pp) ((burst_signal_t)(((burst_long_signal_t)(K1_BOARD_VOLTAGE_PP_TO_VOLT_GAIN_16*pp+K1_BOARD_VOLTAGE_PP_TO_VOLT_OFFSET_16))>>16))
#define K1_BOARD_VOLTAGE_VOLT_TO_PP(ma) ((burst_signal_t)(((burst_long_signal_t)(K1_BOARD_VOLTAGE_VOLT_TO_PP_GAIN_16*ma+K1_BOARD_VOLTAGE_VOLT_TO_PP_OFFSET_16))>>16))


#define K1_BOARD_VOLTAGE_PP_TO_CVOLT(pp) ((burst_signal_t)(((burst_long_signal_t)(K1_BOARD_VOLTAGE_PP_TO_CVOLT_GAIN_10*pp+K1_BOARD_VOLTAGE_PP_TO_CVOLT_OFFSET_10))>>10))
#define K1_BOARD_VOLTAGE_CVOLT_TO_PP(ma) ((burst_signal_t)(((burst_long_signal_t)(K1_BOARD_VOLTAGE_CVOLT_TO_PP_GAIN_10*ma+K1_BOARD_VOLTAGE_CVOLT_TO_PP_OFFSET_10))>>10))
#endif

#ifndef BOARD_CURRENT_SENCE_ENABLED 		
#define BOARD_CURRENT_SENCE_ENABLED 	0
#endif
#if BOARD_CURRENT_SENCE_ENABLED 
#define K1_BOARD_CURRENT_PP_TO_MAMPER(pp) ((burst_signal_t)(((burst_long_signal_t)(K1_BOARD_CURRENT_PP_TO_MAMPER_GAIN_10*pp+K1_BOARD_CURRENT_PP_TO_MAMPER_OFFSET_10))>>10))
#define K1_BOARD_CURRENT_MAMPER_TO_PP(ma) ((burst_signal_t)(((burst_long_signal_t)(K1_BOARD_CURRENT_MAMPER_TO_PP_GAIN_10*ma+K1_BOARD_CURRENT_MAMPER_TO_PP_OFFSET_10))>>10))
#endif
#ifndef K1_FREEMASTER_TYPE
#define K1_FREEMASTER_TYPE K1_BOARD_FREEMASTER_TYPE_NONE
#endif
		
#if K1_FREEMASTER_TYPE==K1_BOARD_FREEMASTER_TYPE_NONE
#define K1_FREEMASTER_ENABLED 0
#else
#define K1_FREEMASTER_ENABLED 1
#endif

#ifndef K1_BOARD_COMMON_VER
#define K1_BOARD_COMMON_VER 0
#endif

#ifndef K1_BOARD_SERIAL_1_ENABLED
#if K1_FREEMASTER_TYPE == K1_FREEMASTER_TYPE_OV_SERIAL_1
#define K1_BOARD_SERIAL_1_ENABLED 1
#else
#define K1_BOARD_SERIAL_1_ENABLED 0
#endif
#endif

#if K1_BOARD_SERIAL_1_ENABLED
#ifndef serial1_INCOM_RING_SIZE_BITS
#define serial1_INCOM_RING_SIZE_BITS 7
#endif
#ifndef serial1_OUTCOM_RING_SIZE_BITS
#define serial1_OUTCOM_RING_SIZE_BITS 7
#endif
#endif

#ifndef K1_BOARD_SERIAL_2_ENABLED
#if K1_FREEMASTER_TYPE == K1_FREEMASTER_TYPE_OV_SERIAL_2
#define K1_BOARD_SERIAL_2_ENABLED 1
#else
#define K1_BOARD_SERIAL_2_ENABLED 0
#endif
#endif

#if K1_BOARD_SERIAL_2_ENABLED
#ifndef serial2_INCOM_RING_SIZE_BITS
#define serial2_INCOM_RING_SIZE_BITS 7
#endif
#ifndef serial2_OUTCOM_RING_SIZE_BITS
#define serial2_OUTCOM_RING_SIZE_BITS 7
#endif
#endif

#ifndef K1_BOARD_SERIAL_3_ENABLED
#if K1_FREEMASTER_TYPE == K1_FREEMASTER_TYPE_OV_SERIAL_3
#define K1_BOARD_SERIAL_3_ENABLED 1
#else
#define K1_BOARD_SERIAL_3_ENABLED 0
#endif
#endif

#if K1_BOARD_SERIAL_3_ENABLED
#ifndef serial3_INCOM_RING_SIZE_BITS
#define serial3_INCOM_RING_SIZE_BITS 7
#endif
#ifndef serial3_OUTCOM_RING_SIZE_BITS
#define serial3_OUTCOM_RING_SIZE_BITS 7
#endif
#endif


#ifndef K1_BOARD_NET_FLOW_ENABLED
#if K1_FREEMASTER_TYPE == K1_FREEMASTER_TYPE_OV_FLOW_PROTO
#define K1_BOARD_NET_FLOW_ENABLED 1
#else
#define K1_BOARD_NET_FLOW_ENABLED 0
#endif
#endif

#if K1_BOARD_NET_FLOW_ENABLED
#ifndef fsincom_RING_SIZE_BITS
#define fsincom_RING_SIZE_BITS 7
#endif
#ifndef fsoutcom_RING_SIZE_BITS
#define fsoutcom_RING_SIZE_BITS 7
#endif
#ifndef K1_BOARD_ADDRESS
#define K1_BOARD_ADDRESS 0xA
#endif
#endif

#ifndef K1_BOARD_NET_SWITCH_ENABLED
#if K1_FREEMASTER_TYPE == K1_FREEMASTER_TYPE_OV_SWITCH_ABONENT
#define K1_BOARD_NET_SWITCH_ENABLED 1
#else
#define K1_BOARD_NET_SWITCH_ENABLED 0
#endif
#endif

#ifndef BURST_PANICS_BOARD_RESET_TIMEOUT_US
#define BURST_PANICS_BOARD_RESET_TIMEOUT_US 0
#endif
