#if (!defined(k1_burst_prf_config_hpp)) && defined(k1_burst_common_h)
#define k1_burst_prf_config_hpp
#else
#error error of using k1-burst-driver.prf.config.hpp
#endif

#define K1_CPU_FREQ_HZ 72000000LL
#define K1_ADC_CURRENT_SENCE_TIME_US 6

//#define K1_CURRENT_SENCE_ENABLED 0
//#define K1_ROTOR_ENCO_TYPE K1_ROTOR_ENCO_TYPE_NONE
//#define K1_ROTOR_POSITION_SENCE_TYPE K1_ROTOR_POSITION_SENCE_TYPE_NONE
//#define K1_SERIAL_TYPE K1_SERIAL_TYPE_NONE

#define BURST_ADC_CHANNEL_COUNT 7
//#define adc_INDEX 

#define FMSTR_REC_TIMEBASE (32768+K1_CONTROL_PERIOD_US)
#define FMSTR_REC_BUFF_SIZE 4000

#define motor_INV3PH_NATIVE_RANGE_LO						0
#define motor_INV3PH_NATIVE_RANGE_HI						(K1_PWM_MODULO-K1_ADC_DELAY)

#define motor_RANGE_VOLTAGE_LO									BURST_SIGNAL_MIN
#define motor_RANGE_VOLTAGE_HI									BURST_SIGNAL_MAX
#define motor_LATERAL_VOLTAGE_RANGE_LO					BURST_SIGNAL_MIN
#define motor_LATERAL_VOLTAGE_RANGE_HI					BURST_SIGNAL_MAX

#define adc_INDEX {0,1,4}
#define motor_CURRENT3PH_ADC_INDEX {0,1,2}

#define K1_TM423ADDR 0x98
#define TMP423_ENABLED 1



#define BURST_PROTECTION_ENABLED 1
#define BURST_PANICS_BOARD_TEMPER_ENABLED 1
#if BURST_PANICS_BOARD_TEMPER_ENABLED == 1
#define K1_BOARD_TEMPER_PP_TO_GRAD( pp ) ((burst_signal_t)(pp))
#define K1_BOARD_TEMPER_GRAD_TO_PP( gr ) ((burst_signal_t)(gr))
#define BURST_PANICS_BOARD_TEMPER_OVERHI_PP K1_BOARD_TEMPER_GRAD_TO_PP(100)
#define BURST_PANICS_BOARD_TEMPER_HI_PP K1_BOARD_TEMPER_GRAD_TO_PP(70)
#define BURST_PANICS_BOARD_TEMPER_LO_PP K1_BOARD_TEMPER_GRAD_TO_PP(-15)
#define BURST_PANICS_BOARD_TEMPER_ULTRALO_PP K1_BOARD_TEMPER_GRAD_TO_PP(-20)
#endif
