#ifndef kalina1_drive_common_hpp
#define  kalina1_drive_common_hpp

#define KALINA1_MOTOR_ENCO_TYPE_NONE 0
#define KALINA1_MOTOR_ENCO_TYPE_HALL 1
#define KALINA1_MOTOR_ENCO_TYPE_INC 2
#define KALINA1_MOTOR_ENCO_TYPE_COMBO 3
#define KALINA1_MOTOR_ENCO_TYPE_ABS 4

#define KALINA1_ACTUATOR_ENCO_TYPE_NONE 0
#define KALINA1_ACTUATOR_ENCO_TYPE_ABS 1


#define KALINA1_BRAKE_TYPE_NONE 0
#define KALINA1_BRAKE_TYPE_VOLTAGE 1
#define KALINA1_BRAKE_TYPE_CURRENT 2

#define  KALINA1_TRACTOR_TYPE_NONE 0
#define  KALINA1_TRACTOR_TYPE_QUBIC_HOLDER 1

#include "kalina1-drive-structure.config.hpp"

#ifdef KALINA1_IM_300
#include "kalina1-drive-im-300.config.hpp"
#endif 

#define KALINA1_MEXO_SLOT_COUNT 4

#ifndef KALINA1_BRAKE_TYPE
#define KALINA1_BRAKE_TYPE KALINA1_BRAKE_TYPE_NONE
#endif
#if KALINA1_BRAKE_TYPE == KALINA1_BRAKE_TYPE_NONE
#define KALINA1_BRAKE_ENABLED 0
#else
#define KALINA1_BRAKE_ENABLED 1
#endif

#ifndef KALINA1_ADC_BITS
#define  KALINA1_ADC_BITS 12
#endif

#if KALINA1_BRAKE_ENABLED == 1

#ifndef KALINA1_ADC_CH_NO_CURRENT_A
#define KALINA1_ADC_CH_NO_CURRENT_A  0
#endif

#ifndef KALINA1_ADC_CH_NO_CURRENT_B
#define KALINA1_ADC_CH_NO_CURRENT_B  1
#endif

#ifndef KALINA1_ADC_CH_NO_CURRENT_C
#define KALINA1_ADC_CH_NO_CURRENT_C  2
#endif

#ifndef KALINA1_ADC_CH_COUNT
#define KALINA1_ADC_CH_COUNT 4
#endif
#ifndef KALINA1_ADC_CH_NO_CURRENT_BR
#define KALINA1_ADC_CH_NO_CURRENT_BR  3
#endif

#else
#ifndef KALINA1_ADC_CH_COUNT
#define KALINA1_ADC_CH_COUNT 3
#endif 
#endif 

#define KALINA1_DRIVE_PMSM_NAME pmsm
#define KALINA1_DRIVE_ACTUATOR_NAME act
#define KALINA1_DRIVE_PS_CROSS_NAME ps_cross
#define KALINA1_DRIVE_PS_LAT_NAME	 ps_lat

#if KALINA1_BRAKE_ENABLED == 1
#define KALINA1_BRAKE_NAME br
#define KALINA1_BRAKE_PS_NAME ps_br
#endif



#if (KALINA1_MOTOR_ENCO_TYPE == KALINA1_MOTOR_ENCO_TYPE_HALL) || (KALINA1_MOTOR_ENCO_TYPE==KALINA1_MOTOR_ENCO_TYPE_COMBO)
#define KALINA1_ROTOR_HALL_ENABLED 1
#else
#define KALINA1_ROTOR_HALL_ENABLED 0
#endif

#if  (KALINA1_MOTOR_ENCO_TYPE == KALINA1_MOTOR_ENCO_TYPE_INC) || (KALINA1_MOTOR_ENCO_TYPE==KALINA1_MOTOR_ENCO_TYPE_COMBO)
#define KALINA1_MOTOR_INC_ENABLED 1
#else
#define KALINA1_MOTOR_INC_ENABLED 0
#endif

#if  (KALINA1_MOTOR_ENCO_TYPE == KALINA1_MOTOR_ENCO_TYPE_ABS)
#define KALINA1_MOTOR_ENCO_ABS_ENABLED 1
#else
#define KALINA1_MOTOR_ENCO_ABS_ENABLED 0
#endif
#endif

#if  (KALINA1_ACTUATOR_ENCO_TYPE == KALINA1_ACTUATOR_ENCO_TYPE_ABS)
#define KALINA1_ACTUATOR_ENCO_ABS_ENABLED 1
#else
#define KALINA1_ACTUATOR_ENCO_ABS_ENABLED 0
#endif


#ifndef KALINA1_CURRENT_IX_A
#define KALINA1_CURRENT_IX_A 0
#endif
#ifndef KALINA1_CURRENT_IX_B
#define KALINA1_CURRENT_IX_B 1
#endif
#ifndef KALINA1_CURRENT_IX_C
#define KALINA1_CURRENT_IX_C 2
#endif

#ifndef KALINA1_ROTOR_OFFSET
#define KALINA1_ROTOR_OFFSET 0
#endif

#ifndef KALINA1_ROTOR_REVERT
#define KALINA1_ROTOR_REVERT false
#endif

#ifndef KALINA1_ROTOR_POLE_COUNT
#define KALINA1_ROTOR_POLE_COUNT 24
#endif

#ifndef KALINA1_ADC_SETUP_PERIOD_BITS
#define KALINA1_ADC_SETUP_PERIOD_BITS 10
#endif

#ifndef KALINA1_VOLTAGE_PP_MAX
#define KALINA1_VOLTAGE_PP_MAX 32767
#endif

#if KALINA1_MOTOR_ENCO_TYPE == KALINA1_MOTOR_ENCO_TYPE_NONE
#define KALINA1_MOTOR_ENCO_ENABLED 0
#else
#define KALINA1_MOTOR_ENCO_ENABLED 1
#endif

#ifndef KALINA1_TRACTOR_TYPE
#define KALINA1_TRACTOR_TYPE KALINA1_TRACTOR_TYPE_NONE
#endif

#if KALINA1_TRACTOR_TYPE == KALINA1_TRACTOR_TYPE_NONE
#define KALINA1_TRACTOR_ENABLED 0
#else 
#define KALINA1_TRACTOR_ENABLED 1
#endif

#if KALINA1_ACTUATOR_ENCO_TYPE == KALINA1_ACTUATOR_ENCO_TYPE_NONE
#define KALINA1_ACTUATOR_ENCO_ENABLED 0
#else
#define KALINA1_ACTUATOR_ENCO_ENABLED 1
#endif

#if KALINA1_ACTUATOR_ENCO_ENABLED || KALINA1_MOTOR_ENCO_ENABLED
#define KALINA1_POSITION_SENCE_ENABLED 1
#else
#define KALINA1_POSITION_SENCE_ENABLED 0
#endif

#define KALINA1_ADC_PP ((1 <<  KALINA1_ADC_BITS) - 1)
#define KALINA1_ADC_SENCE_OFFSET_US (KALINA1_PWM_PERIOD_US- (uint32_t)(KALINA1_ADC_SENCE_TIME_US+0.49) )
#define KALINA1_ADC_SENCE_ONCE_TIME_US (KALINA1_ADC_SENCE_TOTAL_TIME_US/KALINA1_ADC_CH_COUNT)
#define KALINA1_PWM_MODULO ((uint32_t)( 1LL*KALINA1_CPU_FREQ_HZ * KALINA1_PWM_PERIOD_US/ 2000000L  - 1L ))
#define KALINA1_PWM_MAX (KALINA1_PWM_MODULO-KALINA1_ADC_SENCE_TIME_TCK)
#define KALINA1_PWM_MIN 0
#define KALINA1_ADC_SENCE_TIME_TCK ( (uint32_t)( KALINA1_CPU_FREQ_HZ*KALINA1_ADC_SENCE_TIME_US/2000000. + 0.49) )
#define KALINA1_ADC_SENCE_OFFSET_TCK ( (uint32_t)( KALINA1_CPU_FREQ_HZ*KALINA1_ADC_SENCE_OFFSET_US/2000000. + 0.49 ) )
#define KALINA1_PWM_DEADTIME_TCK ( (uint32_t)( KALINA1_CPU_FREQ_HZ*KALINA1_PWM_DEADTIME_US/2000000. + 0.49))
#define KALINA1_BRK_PWM_MIN ( (uint32_t)( 32768.*KALINA1_BRK_SENCE_TIME_US/ KALINA1_PWM_PERIOD_US + 0.49) )
#define KALINA1_BRK_OFFSET ( (uint32_t)( KALINA1_CPU_FREQ_HZ*KALINA1_ADC_SENCE_ONCE_TIME_US*2/2000000. + 0.49 ) )
#define KALINA1_BRK_SENCE_TIME_TCK ( (uint32_t)( KALINA1_CPU_FREQ_HZ*KALINA1_BRK_SENCE_TIME_US/2000000. + 0.49) )
#define KALINA1_CURRENT_MAX_PP ((types::signal_t)(KALINA1_MAX_CURRENT_A * KALINA1_MAX_CURRENT_GAIN +0.49))

#include "kalina1-drive.settings.hpp"

#define KALINA1_NET_FLOW_SNAPSHOT0_SUBA			0x01
#define KALINA1_NET_FLOW_SNAPSHOT0_SUBA_ANSV	0x01
#define KALINA1_NET_FLOW_GOAL0_SUBA				0x02
#define KALINA1_NET_FLOW_VAR_SUBA				0x0B
#define KALINA1_NET_FLOW_VAR_SUBA_ANSW			0x0B
#define KALINA1_NET_FLOW_ECHO_SUBA				0x0E
#define KALINA1_NET_FLOW_ECHO_SUBA_ANSW			0x0E
#define KALINA1_NET_FLOW_SERIAL0_SUBA			0x0F
#define KALINA1_NET_FLOW_SERIAL0_SUBA_ANSW		0x0F
#define KALINA1_NET_FLOW_SNAPSHOT0_SUBA			0x01
#define KALINA1_NET_FLOW_SNAPSHOT0_SUBA_ANSV	0x01
#define KALINA1_NET_FLOW_GOAL0_SUBA				0x02

#ifndef KALINA1_PAYLOAD_ENABLED
#define KALINA1_PAYLOAD_ENABLED 0
#endif